export default {
  files: ["**/*.js", "**/*.jsx", "**/*.ts", "**/*.tsx"],
  languageOptions: {
    parserOptions: {
      parser: "@babel/eslint-parser",
      requireConfigFile: false,
      ecmaFeatures: {
        jsx: true,
      },
    },
  },
  rules: {
    "jsx-a11y/alt-text": "error",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/no-static-element-interactions": "error",
    "no-param-reassign": [
      "error",
      {
        props: true,
        ignorePropertyModificationsFor: ["state"],
      },
    ],
    "prefer-destructuring": "off",
    "simple-import-sort/imports": [
      "error",
      {
        groups: [
          ["^react", "^@?\\w"],
          ["^(@|components)(/.*|$)"],
          ["^\\u0000"],
          ["^\\.\\.(?!/?$)", "^\\.\\./?$"],
          ["^\\./(?=.*/)(?!/?$)", "^\\.(?!/?$)", "^\\./?$"],
          ["^.+\\.?(scss|css)$"],
        ],
      },
    ],
    "simple-import-sort/exports": "error",
    "id-length": [
      2,
      {
        exceptions: ["i", "j", "_", "t"],
        properties: "never",
      },
    ],
    "no-void": "error",
    "func-style": "off",
    eqeqeq: "off",

    "array-callback-return": "error",
    "arrow-body-style": ["error", "as-needed"],
    camelcase: "off",
    "class-methods-use-this": "off",
    "consistent-return": "off",
    curly: ["error", "all"],
    "default-case": "error",
    "default-case-last": "error",
    "default-param-last": "error",
    "dot-notation": ["error", { allowKeywords: true }],
    "grouped-accessor-pairs": "error",
    "guard-for-in": "error",
    "new-cap": "off",
    "no-alert": "error",
    "no-array-constructor": "error",
    "no-caller": "error",
    "no-console": "off",
    "no-constructor-return": "error",
    "no-else-return": ["error", { allowElseIf: false }],
    "no-eval": "error",
    "no-extend-native": "error",
    "no-extra-bind": "error",
    "no-implied-eval": "error",
    "no-inner-declarations": "error",
    "no-invalid-this": "error",
    "no-iterator": "error",
    "no-label-var": "error",
    "no-labels": "error",
    "no-lone-blocks": "error",
    "no-loop-func": "error",
    "no-multi-str": "error",
    "no-nested-ternary": "error",
    "no-new": "error",
    "no-new-func": "error",
    "no-new-wrappers": "error",
    "no-object-constructor": "error",
    "no-octal-escape": "error",
    "no-proto": "error",
    "no-process-exit": "off",
    "no-restricted-properties": [
      "error",
      {
        object: "assert",
        property: "equal",
        message: "Use assert.strictEqual instead of assert.equal.",
      },
      {
        object: "assert",
        property: "notEqual",
        message: "Use assert.notStrictEqual instead of assert.notEqual.",
      },
      {
        object: "assert",
        property: "deepEqual",
        message: "Use assert.deepStrictEqual instead of assert.deepEqual.",
      },
      {
        object: "assert",
        property: "notDeepEqual",
        message:
          "Use assert.notDeepStrictEqual instead of assert.notDeepEqual.",
      },
    ],
    "no-return-assign": "error",
    "no-script-url": "error",
    "no-self-compare": "error",
    "no-sequences": "error",
    "no-shadow": "error",
    "no-throw-literal": "error",
    "no-undef": ["error", { typeof: true }],
    "no-undef-init": "error",
    "no-undefined": "off",
    "no-underscore-dangle": "off",
    "no-unmodified-loop-condition": "error",
    "no-unneeded-ternary": "error",
    "no-unreachable-loop": "error",
    "no-unused-expressions": "error",
    "no-unused-vars": [
      "error",
      {
        args: "all",
        argsIgnorePattern: "^_",
        caughtErrors: "all",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "no-useless-assignment": "error",
    "no-useless-call": "error",
    "no-useless-computed-key": "error",
    "no-useless-concat": "error",
    "no-useless-constructor": "error",
    "no-useless-rename": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "object-shorthand": ["error", "properties"],
    "operator-assignment": "error",
    "prefer-arrow-callback": "error",
    "prefer-const": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    radix: "error",
    "require-unicode-regexp": "error",
    strict: ["error", "global"],
    "symbol-description": "error",
    "unicode-bom": "error",
    yoda: ["error", "never", { exceptRange: true }],
    "no-restricted-syntax": "off",
    "import/no-extraneous-dependencies": "off",
    "no-constant-condition": "error",
    "no-empty-function": "off",
    "no-extra-semi": "error",
    "no-loss-of-precision": "error",
    "max-classes-per-file": "off",
    "no-continue": "off",
    "no-plusplus": "off",
    "import/extensions": "off",
  },
};
